### ISSUE TITLE
PICS: Block index out of range: 1

### ISSUE THREAD

**Issue by Einstein42** [sunspec/pysunspec#12]
git cloned your repo
sudo python setup.py install 
```
$ pysunspec_test.py 
pySunSpec version: 1.0.7
Test device path: /usr/local/lib/python2.7/dist-packages/sunspec/core/test/devices

Traceback (most recent call last):
  File "/usr/local/bin/pysunspec_test.py", line 13, in <module>
    test.test_all()
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/test/test_all.py", line 42, in test_all
    (count_run, count_passed, count_failed) = module.test_all(pathlist, stop_on_failure)
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/test/test_device.py", line 561, in test_all
    if test(pathlist) is True:
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/test/test_device.py", line 402, in test_device_from_pics
    d1.from_pics(filename='pics_test_device_1.xml', pathlist=pathlist)
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/device.py", line 111, in from_pics
    raise SunSpecError('Error loading PICS: %s' % str(e))
sunspec.core.util.SunSpecError: Error loading PICS: Block index out of range: 1
```

Checked the path shown:

```
$ ls /usr/local/lib/python2.7/dist-packages/sunspec/core/test/devices
mbmap_test_device_1_a.xml  mbmap_test_device_2.xml    mbmap_test_inverter_3.xml  pics_test_inverter_2.xml
mbmap_test_device_1_b.xml  mbmap_test_device_3.xml    pics_test_device_1.xml
mbmap_test_device_1_c.xml  mbmap_test_inverter_1.xml  pics_test_device_2.xml
mbmap_test_device_1.xml    mbmap_test_inverter_2.xml  pics_test_inverter_1.xml
```

What am I missing?

**Comment by Einstein42** [comment]
Instead of cloning. I grabbed the release and tried again, worked fine. Closing this as ignorant consumer.
