### ISSUE TITLE
error running the pysunspec_test.py file

### ISSUE THREAD

**Issue by durvesh09** [sunspec/pysunspec#35]
Receive following error on running the test file: 

sudo python pysunspec_test.py
pySunSpec version: 1.0.8
Test device path: /usr/local/lib/python2.7/dist-packages/sunspec/core/test/devices

Traceback (most recent call last):
  File "pysunspec_test.py", line 13, in <module>
    test.test_all()
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/test/test_all.py", line 58, in test_all
    (count_run, count_passed, count_failed) = module.test_all(pathlist, stop_on_failure)
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/test/test_device.py", line 577, in test_all
    if test(pathlist) is True:
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/test/test_device.py", line 418, in test_device_from_pics
    d1.from_pics(filename='pics_test_device_1.xml', pathlist=pathlist)
  File "/usr/local/lib/python2.7/dist-packages/sunspec/core/device.py", line 127, in from_pics
    raise SunSpecError('Error loading PICS: %s' % str(e))
sunspec.core.util.SunSpecError: Error loading PICS: Block index out of range: 1

What could be the reason ?

**Comment by jbm950** [comment]
The models directory is a sub-repository and so an additional command would be needed to acquire that when downloading the code. Please see the [pySunSpec subsection](https://github.com/sunspec/pysunspec/blob/master/README.md#pysunspec) of the Installation instructions on the README.
